// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDxZrFsfAM02GoDmHzrOYStT_UqnRSOpE',
    appId: '1:100266890632:web:87561370fec9114b5d163d',
    messagingSenderId: '100266890632',
    projectId: 'quotemyfence-2',
    authDomain: 'quotemyfence-2.firebaseapp.com',
    storageBucket: 'quotemyfence-2.firebasestorage.app',
    measurementId: 'G-W33E94PCRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz8dxpdGIUtwpMXIjhiOUWpUVsRdV3FYg',
    appId: '1:100266890632:android:133bf8a9e1be12975d163d',
    messagingSenderId: '100266890632',
    projectId: 'quotemyfence-2',
    storageBucket: 'quotemyfence-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE1nswyMW2Y-gYTXckEmJ-sAzxMQbhk5A',
    appId: '1:100266890632:ios:b4032314832746275d163d',
    messagingSenderId: '100266890632',
    projectId: 'quotemyfence-2',
    storageBucket: 'quotemyfence-2.firebasestorage.app',
    iosBundleId: 'com.example.quotefence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE1nswyMW2Y-gYTXckEmJ-sAzxMQbhk5A',
    appId: '1:100266890632:ios:b4032314832746275d163d',
    messagingSenderId: '100266890632',
    projectId: 'quotemyfence-2',
    storageBucket: 'quotemyfence-2.firebasestorage.app',
    iosBundleId: 'com.example.quotefence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDxZrFsfAM02GoDmHzrOYStT_UqnRSOpE',
    appId: '1:100266890632:web:82923ed72b9293675d163d',
    messagingSenderId: '100266890632',
    projectId: 'quotemyfence-2',
    authDomain: 'quotemyfence-2.firebaseapp.com',
    storageBucket: 'quotemyfence-2.firebasestorage.app',
    measurementId: 'G-S9S897J37T',
  );
}
